piVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt ka production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Aapki email taake renewal warnings mil sakein
    email: rajeelsiddiqui3@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: nginx