kind: PersistentVolume
apiVersion: v1 

metadata:
 name: mongo-pv
 namespace: ammax

spec:
 capacity:
  storage: 1Gi

 accessModes:
 - ReadWriteOnce
 storageClassName: manual
 persistentVolumeReclaimPolicy: Retain

 hostPath:
  path: "/data/mongodb-data"  